name: CI/CD Pipeline (bez VPS)

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run application
        run: node index.js


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy simulation
        run: echo "Deployment successful - no VPS used"